FROM python:3.10.14-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tini \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app

WORKDIR /app
COPY consumer.py /app

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["python", "consumer.py"]
